### ISSUE TITLE
Too fast

### ISSUE THREAD

**Issue by gdcteixeira** [atom/autocomplete-atom-api#10]
Isn't there a way to control the speed with which the autocomplete appears? As it is right now it is too fast to appear which makes it difficult to code.
Maybe the possibility of introducing a small delay in the pop-up options would be nice.

Cheers,
gdcteixeira

**Comment by benogle** [comment]
Yep, there is a setting in the autocomplete-plus settings:

![ac-delay](https://cloud.githubusercontent.com/assets/69169/8783159/eb09e3b6-2ece-11e5-8b67-a2cc285f7735.jpg)
