### ISSUE TITLE
Configuration of minimal length

### ISSUE THREAD

**Issue by neu-rah** [atom/autocomplete-atom-api#11]
Can we have a configuration for minimal characters to trigger auto-complete?
I found suggestions based on one or two characters really annoying and useless 99% of the time, and even if useful, guess we don't need help to type 2 characters.
It would also be nice to list only word started by the typed characters instead of middle letters

Ok, just found that on auto-complete plus, please ignore

**Comment by benogle** [comment]
> Ok, just found that on auto-complete plus, please ignore

So you're good? Closing then...
