### ISSUE TITLE
Autocomplete dialog shows always

### ISSUE THREAD

**Issue by Seppo420** [atom/autocomplete-atom-api#13]
Not sure if this is a feature or a "feature", but hard to see how this wouldn't break everyones workflow.

Case:

I've written foo and then end up wanting to move two lines down. The autocomplete dialog has popped up with options foobar and foobaz.

Not only do I have to click esc, but I have to acknowledge the existence of the dialog and be minorly distracted. This is super annoying when it happens all the time.

Running Atom 1.2.4 on Linux Mint

**Comment by FelipeJz** [comment]
I really hate it, i really will love an option to disable it!

**Comment by FelipeJz** [comment]
Got it: https://discuss.atom.io/t/how-do-i-disable-autocomplete/17131/3

**Comment by 50Wliu** [comment]
Alternatively, disable the "Enable Auto Activation" setting in autocomplete-plus's settings.
