### ISSUE TITLE
Much blinking near the end of file

### ISSUE THREAD

**Issue by DatName** [atom/autocomplete-atom-api#18]
When typing near the end of file (for example, line 85 out of total 90) dropdown menu blinks, trying to figure out best position for itself: either above or below selected line. For example, if I  type "for" and move cursor away from atom application window, list of suggestions doesn't stop blinking at all.

**Comment by lee-dohm** [comment]
This Issue belongs on the [autocomplete-plus package](https://github.com/atom/autocomplete-plus). Would you mind reopening it there?
