### ISSUE TITLE
Disable autocomplete for Markdown files

### ISSUE THREAD

**Issue by maxvoltar** [atom/autocomplete-atom-api#19]
Either disable by default or add ability to disable autocomplete for specific file formats.

**Comment by lee-dohm** [comment]
In the autocomplete-plus package settings, there is both a file name based blacklist and a scope based blacklist:

<img width="750" alt="screen shot 2016-02-25 at 3 31 27 pm" src="https://cloud.githubusercontent.com/assets/1038121/13338234/f871a7d8-dbd4-11e5-89cb-41e707e52cfc.png">

Would this work for you?

**Comment by maxvoltar** [comment]
That was exactly what I needed, thanks Lee!

**Comment by lee-dohm** [comment]
You're welcome! I'm glad I could help :grinning:
