### ISSUE TITLE
Prefix matching is too strict

### ISSUE THREAD

**Issue by benogle** [atom/autocomplete-atom-api#2]
* minimum would be not forcing case matching
* nice to have would be fuzzy matching with a requirement that the first char matches

**Comment by kevinsawicki** [comment]
> nice to have would be fuzzy matching with a requirement that the first char matches

Shouldn't this be handled in autocomplete-plus or else every provider will have to implement fuzzy matching themselves?

**Comment by benogle** [comment]
It's hard to do as several providers might consider a match differently, and score things differently. e.g. 

* Some providers might have suggestions on `.`, but `.` doesnt match any of them
* The symbol provider takes locality into account for sorting. Should autocomplete-plus know about that? Fuzzy matching would hose the sorting from the provider.

It does suck that all providers would need to do it themselves, but there isnt a nice way to unify.

**Comment by benogle** [comment]
this has been added
