### ISSUE TITLE
Show "sentences" that are repeated many times

### ISSUE THREAD

**Issue by KSXGitHub** [atom/autocomplete-atom-api#20]
For example: When `process.stdout.write` appears twice or more in the code, `process.stdout.write` should appears in the code as well.

**Comment by lee-dohm** [comment]
From what I can tell, this has nothing to do with the autocomplete-atom-api provider. You may want to report this on the [autocomplete-plus repository](https://github.com/atom/autocomplete-plus). When you do, please include some steps to reproduce the problem, what you expected to happen and what actually happened. See the [How Do I Write a (Good) Bug Report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) section of the CONTRIBUTING guide for suggestions.
