### ISSUE TITLE
Autocompletion for known members should be there too

### ISSUE THREAD

**Issue by mebjas** [atom/autocomplete-atom-api#3]
Currently the completion is provided for tokens only by name (for example let say typing `get` shows `getCollection()` , `getX()`, `getY()` etc ), but there is no autocompletion for known members of an object, for example
if I have js code:
```js
var p = {x: "obj1", y: "obj2", paramx: 1};
```
so when I type p. it should show completion like `x`, `y`, `paramx` etc

Not just with declarations, if I have used it like
```js
p.xparam = x.getTheParam()
```
then later it should give autocompletion suggestions for both `p.` and `x.`, and this one is easier to implement than other one...

![mar 04 2015 04 04](https://cloud.githubusercontent.com/assets/3007365/6479312/3ae73b7c-c269-11e4-9cf9-d6b24d3685ae.gif)

**Comment by benogle** [comment]
This kind of thing isnt the purview of the this provider. This provider only adds autocompletions for the atom API for use when developing atom packages. e.g. you type `atom.`, and it gives you `project`, `config`, etc.

**Comment by benogle** [comment]
Check out the https://github.com/tststs/atom-ternjs provider. It might be what you are looking for.

**Comment by mebjas** [comment]
I had a small talk with @kevinsawicki over mail, regarding ranking of the strings based on their current usage in the document (or project) and showing the result in sorted order if multiple matches are possible. This will lead to better autocompletion.

**Comment by benogle** [comment]
@mebjas that can be done in the new symbol provider in autocomplete-plus. It is experimental currently, but will be the default provider soon enough. Some locality scoring is being done today see: https://github.com/atom-community/autocomplete-plus/blob/4f560a9fe0c59763abf1b91ffd24294a397e99fe/lib/symbol-provider.coffee#L133-L134

**Comment by mebjas** [comment]
@benogle Currently the scoring is based on the prefix matching of the symbol with the part of symbol typed. I'm proposing maintaining the no of times a particular token has been used in memory too. And later in the `container.sort()` call we add a condition where sorting is altered by this score too if there is multiple perfect match.

Does this sound good?
