### ISSUE TITLE
Doesn't autocomplete in init.coffee

### ISSUE THREAD

**Issue by mnquintana** [atom/autocomplete-atom-api#8]
Currently, Atom API autocomplete seems to not work in `init.coffee`. (Tested in safe mode.)

Can anyone in @atom/feedback confirm?

**Comment by izuzak** [comment]
> Can anyone in @atom/feedback confirm?

Yep, doesn't seems to work for me.

**Comment by benogle** [comment]
Yeah, this is annoying
